# Generated by Django 6.1.1 on 2026-09-16 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('task1_1', 'Task 1.1 — Norasmiy xat (informal e-mail)'), ('task1_2', 'Task 1.2 — Rasmiy xat (formal letter)'), ('task2', 'Task 2 — Blogpost / forum / maqola')], max_length=20, verbose_name='Topshiriq turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('prompt_text', models.TextField(verbose_name='Topshiriq matni (savol)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Writing mavzusi (mock)',
                'verbose_name_plural': 'Writing mavzulari (mock)',
                'ordering': ['task_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WritingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('mock', 'Mock (bizning mavzu)'), ('own', "O'z savoli")], default='mock', max_length=8, verbose_name='Rejim')),
                ('task_type', models.CharField(choices=[('task1_1', 'Task 1.1 — Norasmiy xat (informal e-mail)'), ('task1_2', 'Task 1.2 — Rasmiy xat (formal letter)'), ('task2', 'Task 2 — Blogpost / forum / maqola')], max_length=20, verbose_name='Topshiriq turi')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha')),
                ('prompt_text', models.TextField(verbose_name='Savol matni')),
                ('answer_text', models.TextField(verbose_name='Talaba javobi')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Ball')),
                ('max_score', models.PositiveIntegerField(default=5, verbose_name='Maksimal ball')),
                ('level', models.CharField(blank=True, max_length=10, verbose_name='Daraja')),
                ('feedback_json', models.JSONField(blank=True, default=dict, verbose_name='AI izohi')),
                ('credits_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan kredit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writing natijasi',
                'verbose_name_plural': 'Writing natijalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
