# Generated by Django 6.1.1 on 2026-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=3, verbose_name="Kredit (o'z savollari uchun)"),
        ),
    ]
